import {
  Rows3, Rows4, AlignVerticalDistributeCenter, TriangleRight, Columns3, Scaling, Fan,
  Timer, Target, Rainbow, Cone, Shell,
  Radar, Grid2x2, Aperture, Bubbles, Radio, Plane, Disc3, Rocket,
  Activity, Spline, Mountain, TrendingUpDown, AudioWaveform, Waypoints,
  type LucideIcon,
} from 'lucide-react';
import type { FibToolId } from './fibModel.ts';

/** Rail and menu icon for each Fibonacci tool. */
export const FIB_TOOL_ICONS: Record<FibToolId, LucideIcon> = {
  fibr: Rows3,
  fibe: Rows4,
  fibx: AlignVerticalDistributeCenter,
  fibf: TriangleRight,
  fibtz: Columns3,
  fibc: Scaling,
  fibsr: Fan,
  fibtt: Timer,
  fibo: Target,
  fiba: Rainbow,
  fibw: Cone,
  fibs: Shell,
  gannf: Radar,
  gannb: Grid2x2,
  ganns: Aperture,
  dedek: Bubbles,
  sonic: Radio,
  ssonic: Plane,
  gsonic: Disc3,
  gssonic: Rocket,
  xabcd: Activity,
  abcd: Spline,
  hs: Mountain,
  ew5: TrendingUpDown,
  ewabc: AudioWaveform,
  gartley: Waypoints,
  bat: Waypoints,
  bfly: Waypoints,
  crab: Waypoints,
  shark: Waypoints,
  cypher: Waypoints,
};
